### ISSUE TITLE
imgs.tsv not exist

### ISSUE THREAD

**Issue by zhiyustar** [OpenMatch/MARVEL#1]
The img.csv file does not seem to exist in the webqa dataset you provided.
```
FileNotFoundError: [Errno 2] No such file or directory: '../data/WebQA/imgs.tsv'

**Comment by whale-z** [comment]
hi, you can follow the [WebQA project instructions](https://github.com/WebQnA/WebQA?tab=readme-ov-file) and download imgs.tsv from [this link](https://drive.google.com/drive/folders/1ApfD-RzvJ79b-sLeBx1OaiPNUYauZdAZ).
