### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for MultiModal: 	Unexpected key(s) in state_dict: "clip_model.vision_model.embeddings.position_ids". 

### ISSUE THREAD

**Issue by bixie6868** [OpenMatch/MARVEL#2]
I downloaded the CLIP, T5-ance, and OpenMatch.marvel-ance-webqa models for use in my code. But when I run this code:
t5_tokenizer, model, image_processor = load_model(args, device) 
model.load_state_dict(torch.load(args.checkpoint)['model'])

I get the following error:
RuntimeError: Error(s) in loading state_dict for MultiModal:
Unexpected key(s) in state_dict: 'clip_model.vision_model.embeddings.position_ids'.

Could you help me figure out what's going wrong?"

**Comment by mssssss123** [comment]
Please make sure the relevant package versions are consistent with the ones we provide.
For example, transformers==4.22.2 and clip==1.0.

If you still have questions, please contact us.
